/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root";
import { Route as CommunicationRouteImport } from "./app/routes/communication";
import { Route as IndexRouteImport } from "./app/routes/index";

const CommunicationRoute = CommunicationRouteImport.update({
  id: "/communication",
  path: "/communication",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/communication": typeof CommunicationRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/communication": typeof CommunicationRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/communication": typeof CommunicationRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/communication";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/communication";
  id: "__root__" | "/" | "/communication";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CommunicationRoute: typeof CommunicationRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/communication": {
      id: "/communication";
      path: "/communication";
      fullPath: "/communication";
      preLoaderRoute: typeof CommunicationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunicationRoute: CommunicationRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
